# -*- coding: utf-8 -*-
"""student scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIWL_9v51sy2YvvR4B4xqz33NEUxfTbc
"""



import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Generate synthetic student data: hours studied vs. scores
np.random.seed(0)
hours_studied = 5 * np.random.rand(100, 1)
scores = 50 + 5 * hours_studied + np.random.randn(100, 1) * 5 # Base score 50, plus 5 points per hour, with some noise

# Create a Linear Regression model
model = LinearRegression()

# Train the model
model.fit(hours_studied, scores)

# Make a prediction for a student who studied for 3 hours
hours_new = np.array([[3]])
predicted_score = model.predict(hours_new)

print(f"Predicted score for studying 3 hours: {predicted_score[0][0]:.2f}")

# Plot the results
plt.scatter(hours_studied, scores)
plt.plot(hours_studied, model.predict(hours_studied), color='red')
plt.xlabel('Hours Studied')
plt.ylabel('Score')
plt.title('Linear Regression: Hours Studied vs. Scores')
plt.show()